name: sts_chat_client
description: Cross-platform real-time voice chat client for a private server.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_tts: ^4.2.3
  http: ^1.2.2
  livekit_client: ^2.2.7
  permission_handler: ^11.3.1
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
